# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deployCI

on:
  push:
    branches: [ "main" ] # 触发事件

jobs:
  build:

    runs-on: ubuntu-latest # 运行环境

    #strategy: #策略模式
     # matrix:
      #  node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3 #下载最新代码
    - name: 使用node v16
      uses: actions/setup-node@v3 # 下载对应node版本
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run docs:build
    - name: 部署阿里云 # 部署到云服务器，使用easingthemes/ssh-deploy@v2.1.1，通过ssh的方式连接
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 私钥，公钥拷贝到服务器在/root/.ssh/authorized_keys中中
          ARGS: -avzr --delete # 对于任何初始/必需的rsync标志，默认-avzr --delete，如果目录下有其他不可删除文件或文件夹可以用--exclude忽略，如--exclude /uploads/
          SOURCE: "docs/.vuepress/dist" # 源目录
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # 服务器地址
          REMOTE_USER: ${{secrets.REMOTE_USER}} # 连接用户名
          TARGET: ${{ secrets.REMOTE_TARGET }} # 目标部署目录
